[package]
name = "cli_demo"
version = "0.1.0"
authors = ["gugray <zydeodict@gmail.com>"]
edition = "2018"

[dependencies]
hanzi_lookup = { path = "../hanzi_lookup" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.90"
serde_json = "1.0"
